language: ruby
rvm:
  - 2.1.3
before_install: gem install bundler -v 1.10.5
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - DB_NAME=travis_ci_test DB_USER=postgres
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
